[package]
name = "ginlon_test_cargo"
version = "0.1.0"
edition = "2021"
license="MIT"
description = "A test cargo project"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
