[package]
name = "hello-wasm"
version = "0.1.0"
edition = "2021"
authors = ['Ginlon<ginlon5241@gmail.com>']
description = "A simple example of a WASM project"
license = "MIT/Apache-2.0"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"